# Generated by Django 4.2.27 on 2026-01-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения вопроса', verbose_name='Порядок')),
                ('question_type', models.CharField(choices=[('text', 'Текстовый ответ'), ('photo', 'Фото'), ('choice', 'Выбор из вариантов'), ('info', 'Информационное сообщение')], default='text', max_length=20, verbose_name='Тип вопроса')),
                ('text', models.TextField(help_text='Поддерживает HTML-форматирование для Telegram', verbose_name='Текст вопроса')),
                ('choices', models.TextField(blank=True, help_text='Для типа "Выбор": введите варианты через запятую (например: да, нет)', null=True, verbose_name='Варианты ответа')),
                ('image', models.ImageField(blank=True, help_text='Изображение для отправки с вопросом', null=True, upload_to='questions/', verbose_name='Изображение')),
                ('field_name', models.CharField(blank=True, help_text='Техническое имя поля для сохранения ответа (например: full_name, phone)', max_length=100, null=True, verbose_name='Имя поля')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя в Telegram')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия в Telegram')),
                ('is_team_member', models.BooleanField(default=False, verbose_name='Член команды')),
                ('is_registration_complete', models.BooleanField(default=False, verbose_name='Регистрация завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_admin.question', verbose_name='Текущий вопрос')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Текстовый ответ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='responses/%Y/%m/%d/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bot_admin.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bot_admin.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
