# Generated by Django 4.2.27 on 2026-01-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе заполнения'), ('completed', 'Заполнена'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Позиция в команде')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='ФИО')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес проживания')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('passport_main', models.ImageField(blank=True, null=True, upload_to='applications/passports/', verbose_name='Паспорт (главный разворот)')),
                ('passport_registration', models.ImageField(blank=True, null=True, upload_to='applications/passports/', verbose_name='Паспорт (прописка)')),
                ('snils', models.ImageField(blank=True, null=True, upload_to='applications/snils/', verbose_name='СНИЛС')),
                ('inn', models.ImageField(blank=True, null=True, upload_to='applications/inn/', verbose_name='ИНН')),
                ('marital_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Семейное положение')),
                ('children', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дети')),
                ('emergency_contact', models.TextField(blank=True, null=True, verbose_name='Контакты близких')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='bot_admin.userprofile', verbose_name='Профиль Telegram')),
            ],
            options={
                'verbose_name': 'Анкета сотрудника',
                'verbose_name_plural': 'Анкеты сотрудников',
                'ordering': ['-created_at'],
            },
        ),
    ]
